version: '3'
services:

  mongo:
    image: mongo:3.6
    container_name: database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - "mongodata:/data/db"
    ports:
      - "2017:27017"
    command: mongod

  nginx:
    image: nginx:1.15.4
    container_name: static
    volumes:
      - ./config/dev.nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
      - "F:/docs/music/mlp/My Little Pony Ost/mlpost:/docs/music/mlpost"
      - "D:/Documents/Music/MAv16/Artists:/docs/music/mlpfa"
    ports:
      - "2012:80"
    command: nginx -g 'daemon off;'

volumes:
  mongodata:
