version: '3'
services:

  mongo:
    image: mongo:3.6
    container_name: mongo
    #environment:
    #  - MONGO_INITDB_ROOT_USERNAME=root
    ##  - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - "mongodata:/data/db"
    ports:
      - 27017:27017

  nginx:
    image: nginx
    volumes:
    - ./config/nginx.dev.conf:/etc/nginx/conf.d/dev.conf
    ports:
    - "8080:80"
    environment:
    #- NGINX_HOST=foobar.com
    #- NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/dev.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

volumes:
  mongodata:
