secret: secret_replace_me
users:
- username: admin
  password: '1'
  roles:
  - admin
accessToken:
  expiresInMinutes: 60000
  secret: access_replace_me
refreshToken:
  expiresInMinutes: 300000
  secret: refresh_replace_me
http:
  bodyLimitInKb: 2048
  port: 3022
  disableCache: true
  cors:
    enabled: true
    origin: "http://localhost:3000"
logs:
  dirPath: "./logs/"
mongoose:
  host: 127.0.0.1
  port: 2027
  database: ''
  username: user
  password: password
  options:
    server:
      socketOptions:
        keepAlive: 1
